### ISSUE TITLE
FileNotFoundException on execution

### ISSUE THREAD

**Issue by fleed** [agc93/Cake.AutoRest#1]
Hi

I'm using Cake.AutoRest trying to automatically generate client from my API.
My pipeline is: build -> generate swagger file (see [this issue on Cake.NSwag](https://github.com/agc93/Cake.NSwag/issues/5)) -> generate client with Cake.AutoRest

This is an extract of the `build.cake` file:

```csharp
#tool "AutoRest"
#addin nuget:?package=Cake.AutoRest


Task("GenerateClients")
    .IsDependentOn("Rebuild")
    .Does(() => {
        var assemblyPath = softwareBinDirectory.ToString() + "/Software.exe";
        NSwag.FromWebApiAssembly(assemblyPath).ToSwaggerSpecification("./swagger.json");
    AutoRest.Generate("./swagger.json", settings =>
        settings.UseNamespace("Cake")
            .UseClientName("Cake.AutoRest")
            .AddHeaderComment("Generated by Cake.AutoRest")
            .WithGenerator(CodeGenerator.AzureCSharp)
            .OutputToDirectory("./dist/client"));
```

Getting the following output with error:

```text
========================================
GenerateClients
========================================
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'AutoRest.Core, Version=0.17.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at AutoRest.Program.Main(String[] args)
An error occured when executing task 'GenerateClients'.
Error: Azure AutoRest: Process returned an error (exit code -532462766).
Process terminated with code 1.
```

I can find the AutoRest.Core assembly in the following directory: `./tools/AutoRest/tools`

**Comment by agc93** [comment]
I can replicate your issue @fleed and it looks like Azure has changed how they build their NuGet package. 

You can work around this by using 0.16.0 of their package using the following directive at the top of your script:

``` csharp
#tool nuget:?package=AutoRest&version=0.16.0
```

**Background:**  
For some reason (I honestly have no idea what the intention is), they have the executable without any of the supporting libraries in the `lib/net451` TFM, which is tripping up Cake's tool resolver. It's correctly locating `AutoRest.exe` but since that TFM doesn't include the DLLs it needs, AutoRest itself is falling over. I'll have to see if I can either a) use the tool paths to ignore the "broken" TFM, or b) find out why AutoRest is package that way.

**Comment by fleed** [comment]
Thank you so much!

**Comment by agc93** [comment]
@fleed The Azure guys have fixed their package, so delete the tools/AutoRest folder and re-run your build and it should now work as expected.

**Comment by fleed** [comment]
It works now, thanks

**Comment by agc93** [comment]
Great! Let me know if you see any more issues.
